
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  labels:
    app: jenkins-server
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: jenkins-server
  nodeSelector: 
    app: jenkins-server
  type: LoadBalancer
