apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  labels:
    app: jenkins-server
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: jenkins-server
  type: LoadBalancer
